apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: torproxy
    app.kubernetes.io/managed-by: kustomize
  name: manager-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["tor.fulvio.dev"]
  resources: ["torbridgeconfigs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["tor.fulvio.dev"]
  resources: ["torbridgeconfigs/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["tor.fulvio.dev"]
  resources: ["torbridgeconfigs/finalizers"]
  verbs: ["update"]
