# permissions for end users to edit torbridgeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: torproxy
    app.kubernetes.io/managed-by: kustomize
  name: torbridgeconfig-editor-role
rules:
- apiGroups:
  - tor.stack.io
  resources:
  - torbridgeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tor.stack.io
  resources:
  - torbridgeconfigs/status
  verbs:
  - get
