apiVersion: tor.stack.io/v1beta1
kind: TorBridgeConfig
metadata:
  name: torbridgeconfig-sample
  labels:
    app.kubernetes.io/name: torproxy
    app.kubernetes.io/managed-by: kustomize
spec:
  image: dperson/torproxy
  orPort: 9001
  dirPort: 9030
  socksPort: 9050
  hiddenServiceDir: /var/lib/tor/hidden_service/
  hiddenServicePort: 80
  hiddenServiceTarget: 127.0.0.1:80